name: Mattias Cibien
markdown: redcarpet
url: https://www.mattiascibien.net
author: Mattias Cibien
copyright: 2015 Mattias Cibien
higlighter: rouge

permalink: /blog/:title/

collections:
  - projects
  #- daz-studio-content
  
sass:
  style: :compressed

redcarpet:
    extensions: ["tables"]

social:
  #facebook: http://facebook.com/mattiascibienweb
  twitter: http://twitter.com/mattiascibien
  github: http://github.com/mattiascibien
  linkedin: https://www.linkedin.com/in/mattiascibien
  deviantart: http://mattiascibien.deviantart.com/
  google: http://google.com/+MattiasCibienNet
  
gems:
  - jekyll-archives
  - jekyll-sitemap
  
jekyll-archives:
  enabled: 
   - month 
   - tags
  layouts:
    tag: tag-archive
    month: monthly-archive
  permalinks:
    tag: /blog/tag/:name/
    month: /blog/:year/:month/
    
include: [".htaccess"]